language: c

compiler:
    - gcc
    
git:
  depth: 1

env: CTEST_OUTPUT_ON_FAILURE=1

install:
    - sudo pip install cpp-coveralls --use-mirrors
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake python3-minimal

script:
    - cmake . -DCMAKE_C_FLAGS='-O0 --coverage' -DCMAKE_CXX_FLAGS='-O0 --coverage'
    - make
    - make test

after_success:
    - coveralls

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/d4ac611092a6de1b9db4
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false
