language: c

compiler:
    - gcc

env: CTEST_OUTPUT_ON_FAILURE=1

install:
    - sudo pip install cpp-coveralls --use-mirrors
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake

script:
    - cmake . -DCMAKE_C_FLAGS='-O0 --coverage' -DCMAKE_CXX_FLAGS='-O0 --coverage'
    - make
    - make test

after_success:
    - coveralls --exclude-pattern '.*CMake[^/]+\.c(?:pp)?'
