language: c

compiler:
    - gcc

install:
    - sudo pip install cpp-coveralls --use-mirrors
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake

script:
    - cmake .
    - make
    - make test

after_success:
    - coveralls
